import * as assert from 'uvu/assert'
import { resolve, getFormat, getSource, transformSource } from './index.js'
import { suite } from 'uvu'

const test = suite('esm-loader-svelte')
const files = {
  svelte: 'file:///src/components/Counter.svelte',
  style: 'file:///static/styles/layout.css',
}

test('resolve', async () => {
  const result = await resolve(files.svelte)
  assert.match(result.url, new RegExp(files.svelte))
})

test('getFormat', async () => {
  const result = await getFormat(files.svelte)
  assert.is(result.format, 'module')
})

test('getSource on .css', async () => {
  const source = 'body { color: blue }'
  const result = await getSource(files.style)
  assert.match(result.source, '')
})

test('transformSource on .svelte', async () => {
  const source = `
    <script>
      const hello = 1
    </script>
    <div>
      <span>{hello}</span>
    </div>
    <style>
      span { color: red }
    </style>
  `
  const result = await transformSource(source, { url: files.svelte })
  assert.match(result.source, new RegExp(files.svelte))
  assert.match(result.source, /generated by Svelte/)
})

test.run()
