import * as assert from 'uvu/assert'
import { getFormat, resolve, transformSource } from './index.js'
import { suite } from 'uvu'

const file = 'file:///src/components/Counter.svelte'
const test = suite('esm-loader-svelte')

test('resolve', async () => {
  const result = await resolve(file)
  assert.match(result.url, new RegExp(file))
})

test('getFormat', async () => {
  const result = await getFormat(file)
  assert.is(result.format, 'module')
})

test('transformSource', async () => {
  const source = `
    <script>
      const hello = 1
    </script>
    <div>
      <span>{hello}</span>
    </div>
    <style>
      span { color: red }
    </style>
  `
  const result = await transformSource(source, { url: file })
  assert.match(result.source, new RegExp(file))
  assert.match(result.source, /generated by Svelte/)
})

test.run()
