import * as assert from 'uvu/assert'
import { suite } from 'uvu'
import { resolve, getFormat, transformSource } from './index.js'

const test = suite('esm-loader-svelte')
const url = 'file:///components/Counter.svelte'

test('resolve on svelte file = success', async () => {
  const result = await resolve(url)
  assert.is(result.url, url)
})

test('getFormat', async () => {
  const result = await getFormat(url)
  assert.is(result.format, 'module')
})

test('transformSource', async () => {
  const source = `
    <script>
      const hello = 1
    </script>
    <div>
      <span>{hello}</span>
    </div>
    <style>
      span { color: red }
    </style>
  `
  const result = await transformSource(source, { url })
  assert.match(result.source, new RegExp(url))
  assert.match(result.source, /generated by Svelte/)
})

test.run()
